name: project-one-backend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # these steps happens one by one

      - name: fixing permisson for batect
        run: chmod +x batect

      - name: Install Dependencies
        run: ./batect install-dep

      - name: Run Test Cases
        run: ./batect test-ci

      - name: Perform Linting
        run: ./batect lint

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku Container Registery
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build docker image and push to heroku registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a project-one-back-end web

      - name: Run docker image on heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a project-one-back-end web
